config/routes.rb
Rails.application.routes.draw do


  root to: 'posts#index'
  devise_for :users, :controllers => {registrations: 'registrations'}
  resources :users, :posts

  get "posts", to: "posts#index", as: 'show_posts'
  post "posts", to: "posts#create", as: 'create'
  get "posts/new", to: "posts#new", as: 'new'
  get "posts/:id", to: "posts#show", as: 'show_post'
  put "posts/:id", to: "posts#update", as: 'update_post'
  delete "posts", to: "posts#destroy", as: 'destroy_post'
  get "posts/:id/edit", to: "posts#edit"

  post 'posts/:id', to: "comments#create", as: 'create_comment'

  get 'posts/:id', to: "comments#edit", as: 'edit_comment'

  delete 'comments/delete', to: "comments#delete", as: 'destroy_comment'

  get 'tags/:id', to: 'tags#show', as: 'tag'
  get 'tag/add', to: 'tags#add', as: 'add_tag'
  post 'tags/create', to: "tags#create", as: 'create_tag'
  put 'tags/:id', to: 'tags#add_existing', as: 'add_existing_tag'
  get 'users/:id', to: 'users#show', as: 'show_user'





end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
    has_and_belongs_to_many :tags
    validates :title, :body, presence: true
    searchkick
end

app/models/tag.rb
class Tag < ActiveRecord::Base

	has_and_belongs_to_many :users
	has_and_belongs_to_many :posts
	searchkick
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments, :through => :post
  has_and_belongs_to_many :tags
  searchkick

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :organization) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
      post = Post.find(params[:id])
      comment =  Comment.new(body: params[:comment][:body], post_id: post.id, user_id: current_user.id)
      comment.save
      redirect_to post_path(post)

  end

  def edit
    @comment = Comment.find(params[:id])
    render "edit"
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    @comment.save
    redirect_to @comment.post
  end

  def delete

  end

  def comment_params
    params.require(:comment).permit(:body, :post_id)
 	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def index
    if params[:query].present?
      @posts = Post.search(params[:query])
    else
      @posts = Post.all
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comment = Comment.new
    @comments = Comment.where("post_id = ?", params[:id])
  end

  def new
    @post = current_user.posts.build
    render "new"
  end

  def create

    if Post.new(title: params[:post][:title], body: params[:post][:body]).valid?
      raw_tags = params[:post][:tags]
      parsed_tags = raw_tags.split(", ")
      post = Post.new(title: params[:post][:title], body: params[:post][:body], user_id: current_user.id)
      parsed_tags.each do |new_tag_name|
        relevant_tag_dict = {}
        Tag.all.each {|tag|  relevant_tag_dict[tag.name] = tag}
        if relevant_tag_dict.key? new_tag_name
          post.tags << relevant_tag_dict[new_tag_name]
        else
          post.tags << Tag.create([{name: new_tag_name}])
        end
      end
      post.save
      redirect_to posts_path
    else

    end
  end

  def edit
    @post = Post.find(params[:id])
    render "edit"
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
      @post = Post.find(params[:id])
      @post.destroy
      @post.tags.destroy
      redirect_to posts_path
  end

  def post_params
    params.require(:post).permit(:title, :body)

 	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	public

	def sign_up_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation, :year_started, :year_ended, :organization)
	end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
    @users = @tag.users
    @posts = @tag.posts
  end

  def add
	@tag = current_user.tags.build
    render "add"
  end

   def create
    if Tag.new(name: params[:tag][:name], description: params[:tag][:name]).valid?
      relevant_tag_dict = {}
      Tag.all.each {|tag|  relevant_tag_dict[tag.name] = tag}
      if relevant_tag_dict.key? params[:tag][:name]
        tag = relevant_tag_dict[params[:tag][:name]]
      else
        tag = Tag.create(name: params[:tag][:name], description: params[:tag][:description])
      end
      current_user.tags << tag unless current_user.tags.include? tag
      redirect_to tag
  		end
	end

    def add_existing
    	@tag = Tag.find(params[:id])
    	current_user.tags << @tag
    	redirect_to @tag
  	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    @tags = @user.tags
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/delete.html.erb
<h1>Comments#delete</h1>
<p>Find me in app/views/comments/delete.html.erb</p>

app/views/comments/edit.html.erb
<h1>Edit Post for <%= params[:id] %> <%= link_to "back", post_path(post) %></h1>

<%= simple_form_for @comment, :url => update_comment_path(@comment), :method => :put do |comment|%>
<%= comment.input :body, label: "comment: " %>
  <%= comment.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Lum" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Lum" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %> 
    </main>

    <p class ="notice"><%= notice %></p>
    <p class ="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/posts/edit.html.erb
<h1>Edit Post for <%= params[:id] %> <%= link_to "back", posts_path %></h1>

<%= simple_form_for @post, :url => update_post_path(@post), :method => :put do |post|%>
<%= post.input :title, label: "Title: " %>
<%= post.input :body, label: "Body: " %>
  <%= post.button :submit%>
<% end %>

app/views/posts/index.html.erb
<h2> <%= current_user.organization %> </h2>
  <%= form_tag show_posts_path, method: :get do %>
    <div class="form-group">
      <%= text_field_tag :query, params[:query], class: 'form-control' %>
      <%= submit_tag 'Search', class: 'btn btn-primary' %>
    </div>
  <% end %>
<%= button_to "New Post", new_path(), class: 'btn btn-primary', :method => :get %>
<% @posts.each do |post|
  if post.user.organization == current_user.organization%>
<div class="panel panel-default">
  <div class="panel-body">
  <h2> <%= link_to post.title, post %> </h2>
  <p><%= post.body %> </p>
  <p><%=link_to post.user.name, post.user %> </p>
  <p><%=post.user.created_at %></p>
  <a href="#"><%=link_to "Comments", post %><span class="badge"><%= post.comments.count %></span></a>
  <div class="panel panel-default">
  <div class="panel-body">
  <% post.tags.each do |tag| %>
  <span style="white-space: nowrap;"><%= link_to tag.name, tag %></span>
  <% end %>
  </div>
</div>
  <% if current_user == post.user %>
      <%= button_to "Edit", edit_post_path(post), :class =>"btn btn-primary", :method => :get %>
      <%= button_to "Delete", post, :confirm => "Are you sure?", :class => "btn btn-primary", :method => :delete %>
  <% end %>
  <% end %>
  </div>
</div>
<% end %>

app/views/posts/new.html.erb
<%= simple_form_for @post, :url => create_path(), :method => :post do |post|%>
<%= post.input :title, label: "Title: " %>
<%= post.input :tags, label: "Tags: " %>
<p>Enter a comma delimited list of tags.</p>
<%= post.input :body, label: "Body: " %>
  <%= post.button :submit%>
<% end %>

app/views/posts/show.html.erb







<div class="panel panel-default">
  <div class="panel-body">
  <h2> <%= link_to @post.title, @post %> </h2>
  <p><%= @post.body %> </p>
  <p><%=link_to @user.email, @user %> </p>
  <p><%=@user.created_at %></p>
  <% if current_user == @user %>
    <%= button_to "Edit", edit_post_path(@post), :class => "button small", :method => :get %>
  <% end %>
  
  <% @comments.each do |comment| %>
  <div class="panel panel-default">
  <div class="panel-body">
  <p><%= link_to comment.user.name, comment.user %> | <%= comment.created_at %></p>
  <p><%= comment.body %> </p>
  <% if current_user.id == comment.user_id %>
      <%= button_to "Edit", edit_comment_path(comment), :class => "button small", :method => :get %>
      <%= button_to "Delete", destroy_comment_path(comment), :confirm => "Are you sure?", :class => "button small", :method => :delete %>
  <% end %>
  </div>
  </div>
  
<% end %>

  

<%= simple_form_for @comment, :url => create_comment_path(@post), :method => :post do |comment|%>
<%= comment.input :body, label: "Comment: " %>
<%= comment.button :submit%>
<% end %>
  </div>
</div>

app/views/tags/add.html.erb
<%= simple_form_for @tag, :url => create_tag_path(), :method => :tag do |tag|%>
<%= tag.input :name, label: "Name: " %>
<%= tag.input :description, label: "Description: " %>
  <%= tag.button :submit, class: 'btn btn-primary'%>
<% end %>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>
<p><%= @tag.description if @tag.description %></p>
<h2>Related Users:</h2>
<% @users.each do |user| %>
	<p><%= link_to user.name, user %>
<% end %>
<h2>Related Posts:</h2>
<% @posts.each do |post| %>
  <p><%= link_to post.title, post %> </p>
<% end %>
<%= button_to("Add Tag", add_existing_tag_path(@tag), class: 'btn btn-primary', :method => :put) unless current_user.tags.include? @tag %>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>

              <%= render user if user.organization == current_user.organization%>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3><%= @user.name if @user.name %></h3>
<p> <%= @user.email if @user.email %></p>
<h4>Tags:</h4>
<% @tags.each do |tag| %>
  <p><%= link_to tag.name, tag %> </p>
  <% end %>
<% if current_user == @user %>
<%= button_to "New Tag", add_tag_path(), :class => "button large", :method => :get %>
<% end %>
<h4>Posts:</h4>
<% @posts.each do |post| %>
  <p><%= link_to post.title, post %> </p>
<% end %>
<% if current_user == @user %>
<%= button_to "New Post", new_path(), :class => "button large", :method => :get %>
<% end %>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>